name: Generate Snake

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: Platane/snk@v2.1.0 # Replace with the latest version


      - name: Generate Snake SVG
        uses: Platane/snk@v2
        with:
          github_user_name: Mahmoudemam22
          outputs: dist/github-snake-dark.svg

      - name: Git status
        run: git status

      - name: Commit and push changes
        run: |
          git add dist/
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Update Snake SVG [skip ci]"
          git push origin master

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
